### ISSUE TITLE
修改 worksheet, 按取消產生 exception 無法恢復原有畫面

### ISSUE THREAD

**Issue by nexgus** [nexgus/hgsystem#1]
`Traceback (most recent call last):
  File "C:\MyProjects\hgsystem\works\main_widget.py", line 218, in worksheetCancel
    worksheet = self.customer.history.getRowContentsEx(row)
  File "C:\MyProjects\hgsystem\works\customer.py", line 339, in getRowContentsEx
    record = self.getRowContents(row)
  File "C:\MyProjects\hgsystem\works\customer.py", line 333, in getRowContents
    record = [self.item(row, idx).text() for idx in range(len(self.HEADERS))]
  File "C:\MyProjects\hgsystem\works\customer.py", line 333, in <listcomp>
    record = [self.item(row, idx).text() for idx in range(len(self.HEADERS))]
AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by nexgus** [comment]
Don't know why I cannot reproduce such condition.
