### ISSUE TITLE
取消新增客戶後新增工單, 再按取消產生例外且無法恢復原有畫面

### ISSUE THREAD

**Issue by nexgus** [nexgus/hgsystem#2]
```
Traceback (most recent call last):
  File "C:\MyProjects\hgsystem\works\main_widget.py", line 218, in worksheetCancel
    worksheet = self.customer.history.getRowContentsEx(row)
  File "C:\MyProjects\hgsystem\works\customer.py", line 339, in getRowContentsEx
    record = self.getRowContents(row)
  File "C:\MyProjects\hgsystem\works\customer.py", line 333, in getRowContents
    record = [self.item(row, idx).text() for idx in range(len(self.HEADERS))]
  File "C:\MyProjects\hgsystem\works\customer.py", line 333, in <listcomp>
    record = [self.item(row, idx).text() for idx in range(len(self.HEADERS))]
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by nexgus** [comment]
1. 新增客戶
1. 取消
1. 新增工單
1. 取消 -> 產生例外

**Comment by nexgus** [comment]
Fixed. Please check 0.2.4.
The root cause is, in `main_widget.py`, `MainWidget.customerCancel()`, it set row number before append row(s) to table.
